<div class="rahma_association_section terms_conditions_sec">
		<div class="container">
			<div class="row">
				<div class="col-md-12 d-flex justify-content-center">
					<div class="rahma_association_custom_heading">
							<h3>Terms & Conditions</h3>
					</div>
			</div>
			</div>
		</div>
</div>



<div class="terms_conditions_main_sec text-left">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p>Cancer Patient Care Society – Rahma maintains the Rahmacancercare.com Website (“Site”). The following are the terms of use that govern use of the Site (“Terms of Use”). By using the Site you expressly agree to be bound by these Terms of Use and the Rahmacancercare.com privacy policy and to follow these Terms of Use and all applicable laws and regulations governing use of the Site. Cancer Patient Care Society – Rahma reserves the right to change these Terms of Use at any time, effective immediately upon posting on the Site. Please check this page of the Site periodically. We will note when there are updates to the Terms of Use at the bottom of the Terms of Use. If you violate these Terms of Use, Cancer Patient Care Society – Rahma may terminate your use of the Site, bar you from future use of the Site, and/or take appropriate legal action against you.</p>
					<p>LIMITED LICENSE. You are granted a limited, non-exclusive, revocable and non-transferable license to utilize and access the Site pursuant to the requirements and restrictions of these Terms of Use. Cancer Patient Care Society – Rahma may change, suspend, or discontinue any aspect of the Site at any time. Cancer Patient Care Society – Rahma may also, without notice or liability, impose limits on certain features and services or restrict your access to all or portions of the Site. You shall have no rights to the proprietary software and related documentation, if any, provided to you in order to access the Site. Except as provided in the Terms of Use, you shall have no right to directly or indirectly, own, use, loan, sell, rent, lease, license, sublicense, assign, copy, translate, modify, adapt, improve, or create any new or derivative works from, or display, distribute, perform, or in any way exploit the Site, or any of its contents (including software) in whole or in part.</p>
					
					<ol>
						<li><strong>SITE OPERATION</strong>: United Arab Emirates is our Country of Domicile. Cancer Patient Care Society – Rahma controls this Site from the U.A.E. Cancer Patient Care Society – Rahma makes no representation that this Site is appropriate for use in other locations. If you use this Site from other locations you are responsible for ensuring compliance with local laws. You may not use, export or re-export any materials from this Site in violation of any applicable laws or regulations, including, but not limited to any U.A.E export laws and regulations.<strong>APPLICABLE LAW</strong>. The Laws of the United Arab Emirates shall govern the use of the Site and the Terms of Use, without regards to conflict of laws principals. All disputes arising in connection therewith shall be heard only by a court of competent jurisdiction in U.A.E.</li>
						
						<li><strong>MULTI-CURRENCY PRICED TRANSACTION</strong>, the displayed price and currency selected by you, will be the same price and currency charged to the Card and printed on the Transaction Receipt.<strong>PURCHASES</strong>. Cancer Patient Care Society – Rahma accepts payment by Visa or Mastercard debit and credit cards in AED for its products and services. All online purchases are also governed by the terms and conditions of respective merchant service providers. Please review respective merchant service provider’s user agreement and privacy policy before entering any transaction. Interpretation. These Terms of Use supersede all other written and oral communications or agreements with regard to the subject matters discussed in these Terms of Use. A waiver or modification of these Terms of Use will only be effective if made in writing signed by an authorized officer of Cancer Patient Care Society – Rahma. All refunds will be made onto the original mode of payment.</li>
						
						<li><strong>OFFICE FOREIGN ASSETS CONTROL (OFAC) SANCTIONED COUNTRIES</strong>. Cancer Patient Care Society – Rahma will not trade with or provide any services to individuals and companies owned or controlled by, or acting for or on behalf of, OFAC targeted countries AND individuals, groups, and entities, such as terrorists and narcotics traffickers designated under the OFAC programs that are not country specific.</li>
						
						<li><strong>REPRESENTATIONS BY YOU</strong>. By visiting the Site, you represent, warrant and covenant that (a) you are at least 18 years old; (b) that all materials of any kind submitted by you to Cancer Patient Care Society – Rahma through the Site or for inclusion on the Site will not plagiarize, violate or infringe upon the rights of any third-party including trade secret, copyright, trademark, trade dress, privacy, patent, or other personal or proprietary rights. The customer using the website who are Minor /under the age of 18 shall not register as a User of the website and shall not transact on or use the website.</li>
						
						<li><strong>PERMITTED USE</strong>. You agree that you are only authorized to visit, view and to retain a copy of pages of this Site for your own personal use, that you shall not duplicate, download, publish, modify or otherwise distribute the material on this Site for any purpose other than for personal use, unless otherwise specifically authorized by Cancer Patient Care Society – Rahma to do so. You also agree not to deep-link to the site for any purpose, unless specifically authorized by Cancer Patient Care Society – Rahma to do so. The content and software on this Site is the property of Cancer Patient Care Society – Rahma. The cardholder must retain a copy of transaction records and Merchant policies and rules.</li>
						
						<li><strong>YOUR ACCOUNT</strong>. If you use Cancer Patient Care Society – Rahma Site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your account from any devices, and you agree to accept responsibility for all activities that occur under your account or password. The Site shall not be responsible or liable, directly or indirectly, in any way for any loss or damage of any kind incurred as a result of, or in connection with, your failure to comply with this section.</li>
						
						</ol>
						
						<p><strong>NO COMMERCIAL USE</strong>. This Site may not be used by you for any commercial purposes such as to conduct sales of merchandise or services of any kind. You must obtain Cancer Patient Care Society – Rahma’s prior written consent to make commercial offers of any kind on the Site, whether by advertising, solicitations, links, or any other form of communication. Cancer Patient Care Society – Rahma will investigate and take appropriate legal action against anyone who violates this provision, including without limitation, removing the offending communication from the Site and barring such violators from use of the Site.</p>
						
						<p><strong>LINKS AND SEARCH RESULTS</strong>. The Site may automatically produce search results that reference and/or link to third party sites throughout the World Wide Web. Cancer Patient Care Society – Rahma has no control over these sites or the content within them. Cancer Patient Care Society – Rahma does not guarantee, represent or warrant that the content contained in the sites is accurate, legal and/or inoffensive. Cancer Patient Care Society – Rahma does not endorse the content of any third party site, nor does it make any representation or warranty about these sites, including that they will not contain viruses or otherwise impact your computer. By using the Site to search for or link to another site, you agree and understand that you may not make any claim against Cancer Patient Care Society – Rahma for any damages or losses, whatsoever, resulting from your use of the Site to obtain search results or to link to another site. If you have a problem with a link from the Site, you may notify us at&nbsp;<a href="mailto:info@rahma.org.ae">info@rahmacancercare.com</a>.</p>
						
						<p><strong>COPYRIGHT POLICY</strong>. Cancer Patient Care Society – Rahma may terminate the privileges of any user who uses this Site to unlawfully transmit copyrighted material without a license, express consent, valid defense or fair use exemption to do so. If you submit information to this Site, you warrant that the information does not infringe the copyrights or other rights of third parties.</p>
						
						<p><strong>INTELLECTUAL PROPERTY</strong>. Although Cancer Patient Care Society – Rahma is not responsible for the content, quality or accuracy of data provided by users, compilations of such data, text, information and other materials made available to users through Cancer Patient Care Society – Rahma’s system. The On-line Materials are Cancer Patient Care Society – Rahma’s intellectual property, and are protected by U.S. and international intellectual property laws. The On-line Materials may not be copied or redistributed either in whole or in part without prior written consent of Cancer Patient Care Society – Rahma, except as expressly and specifically permitted under these Terms of Use.</p>
						
						<p>The On-line Materials are and will remain the exclusive property of Cancer Patient Care Society – Rahma. All rights, titles and interests in and to the On-line Materials will be and remain vested solely in Cancer Patient Care Society – Rahma. Under no circumstances will you have any right, directly or indirectly, to own, use, copy, loan, sell, rent, lease, license, sublicense, redistribute, assign or otherwise convey the On- line Materials, or any rights thereto, except as expressly and specifically provided in the Terms of Use. Nothing in these Terms of Use will convey to you any right, title or interest, except that of a license with the express rights and subject to all limitations herein. Nothing in these Terms of Use grants you the right, directly or indirectly, to use the On-line Materials to create a product for resale or to use the On-line Materials in any way that competes with Cancer Patient Care Society – Rahma.</p>
						
						<p>You acknowledge and agree that Cancer Patient Care Society – Rahma will own all rights, titles and interests in and to any copy, translation, modification, adaptation, derivative work or improvement of the On- line Materials made by or for you. At Cancer Patient Care Society – Rahma’s request, you must execute, or obtain the execution of, any instrument that may be necessary to assign these rights, titles or interests to Cancer Patient Care Society – Rahma or perfect these rights, titles or interests in Cancer Patient Care Society – Rahma’s name. DISCLAIMER OF WARRANTY, LIMITATION OF DAMAGES. Cancer Patient Care Society – Rahma MAKES NO WARRANTY OR REPRESENTATION OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTY OF TITLE OR NON-INFRINGEMENT OR IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,NON-INFRINGEMENT OR OTHER VIOLATION OF RIGHTS IN RELATION TO THE AVAILABILITY, ACCURACY, VALIDITY, RELIABILITY OR CONTENT OF THESE PAGES AND/OR THE SITE. Cancer Patient Care Society – Rahma ALSO DOES NOT MAKE ANY REPRESENTATION OR WARRANTY REGARDING THE ACCURACY OR RELIABILITY OF ANY ADVICE, OPINION, STATEMENT OR OTHER INFORMATION THAT IS SUBMITTED, DISPLAYED OR UPLOADED THROUGH THE SITE BY ANY USER. Cancer Patient Care Society – Rahma SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR FOR BUSINESS INTERRUPTION ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SITE, EVEN IF Cancer Patient Care Society – Rahma HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW EXCLUSION OF CERTAIN WARRANTIES OR LIMITATIONS OF LIABILITY, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THE LIABILITY OF Cancer Patient Care Society – Rahma WOULD IN SUCH CASE BE LIMITED TO THE GREATEST EXTENT OF LIABILITY PERMITTED BY LAW.</p>
						
						<p><strong>VIOLATION OF TERMS OF USE</strong>. You understand and agree that in Cancer Patient Care Society – Rahma’s sole discretion, and without prior notice, Cancer Patient Care Society – Rahma may terminate your access to the Site, or exercise any other remedy available and remove any unauthorized user information, if Cancer Patient Care Society – Rahma believes that the information you provide has violated or is inconsistent with these Terms of Use, or violates the rights of Cancer Patient Care Society – Rahma, or any third party, or violates the law. You agree that monetary damages may not provide a sufficient remedy to Cancer Patient Care Society – Rahma for violations of these Terms of Use and you consent to injunctive or other equitable relief for such violations. Cancer Patient Care Society – Rahma may release user information about you if required by law or subpoena.</p>
						
						<p><strong>INDEMNITY</strong>. You agree to indemnify and hold Cancer Patient Care Society – Rahma, its subsidiaries, affiliates, officers, agents and other partners and employees, harmless from any loss, liability, claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of or relating to your use of the Site, including also your use of the Site to provide a link to another site or to upload content or other information to the Site, or your breach of the Terms of Use.</p>
						
						<p><strong>LICENCE GRANTED TO YOU</strong>. By providing materials to Cancer Patient Care Society – Rahma, including by submitting or uploading content or materials for use on the Site you represent and warrant that you or the owner of all rights to such content or materials has expressly granted Cancer Patient Care Society – Rahma an irrevocable world-wide right in all languages and in perpetuity to use and exploit all or any part of the content and materials provided by you. Cancer Patient Care Society – Rahma may publish and distribute any such submitted content or materials at its sole discretion by any method now existing or later developed. You agree that you shall waive all claims and have no recourse against Cancer Patient Care Society – Rahma for any alleged or actual infringement or misappropriation of any proprietary rights in any communication, content or material submitted to Cancer Patient Care Society – Rahma. Any communication or materials you send to Cancer Patient Care Society – Rahma will be treated as non- confidential and non-proprietary and may be disseminated or used by Cancer Patient Care Society – Rahma for any purpose, including, but not limited to, developing, creating, manufacturing or marketing products or services.</p>
						
						<p><strong>ADVERTISING</strong>. The Site may contain advertisements and/or sponsorships. The advertisers and/or sponsors that provide these advertisements and sponsorships are solely responsible for insuring that the materials submitted for inclusion on the Site are accurate and comply with all applicable laws. Cancer Patient Care Society – Rahma is not responsible for the acts or omissions of any advertiser or sponsor.</p>
						
						<p>SEVERABILITY. If any provision of the Terms of Use is held to be invalid, void or unenforceable, the remaining provisions shall nevertheless continue in full force and effect.</p>
						
						<p>Headings  section titles in this Agreement are for convenience and do not define, limit, or extend any provision of this Agreement.</p>

					</div>



			</div>
			</div>
		</div>
</div>